export const FIGURE_TYPE = {
  SHEET: 'sheet',
  BRANCH: 'branch',
  TOPIC: 'topic',
  BOUNDARY: 'boundary',
  RELATIONSHIP: 'relationship',
  SUMMARY: 'summary',
  CONNECTION: 'connection',
  COLLAPSE_EXTEND: 'collapseextend',
  TOPIC_TITLE: 'topictitle',
  RELATIONSHIP_TITLE: 'relationshiptitle',
  NUMBERING: 'numbering',
  IMAGE: 'image',
  LABELS: 'labels',
  LABEL: 'label',
  MARKERS: 'markers',
  MARKER: 'marker',
  INFORMATION: 'information',
  SELECT_BOX: 'selectbox',
  RESIZE_BOX: 'resizebox',
  TOPIC_SELECT_BOX: 'topic_selectbox',
  PLACE_HOLDER_TOPIC: 'placehodertopic',
  MATRIX: 'matrix',
  MATRIX_LABEL: 'matrixlabel',
  MATRIX_CELL: 'matrixcell',
  MATRIX_PLUS: 'matrixplus',
  BOUNDARY_TITLE: 'boundarytitle'
}