export const MODULE_NAME = {
  ADD_RELATIONSHIP: 'addrelationshipmanager',
  COPY_PASTE: 'copypastemanager',
  DRAG: 'dragmanager',
  DROP: 'dropmanager',
  PRE_ADD_FLOATING_TOPIC: 'preaddfloatingtopic',
  SELECTION: 'selectionmanager',
  KEY_BIND: 'keybind',
  EDIT_RECEIVER: 'editreceiver',
  MINI_MAP: 'minimap',
  MOVE_VIEW_PORT: 'moveviewport',
  SEMAPHORE: 'semaphore',
  LAYOUT: 'layout',
  MOUSE_BOX_SELECT: 'mouseboxselect',
  MARKER_MAP: 'markermap',
  MODIFY_CHECK: 'modifycheck',
  SELECT_DRAG: 'selectdragmanager',
  OVERRIDE_STYLE: 'overridestyle',
  SVG_DRAGGABLE: 'svgdraggable',
  UI_STATUS: 'uistatusmanager'
}